"""add portfolio holdings and price alerts

Revision ID: ea2694515be7
Revises: c5cd363a27c1
Create Date: 2026-07-10 04:12:20.479688

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea2694515be7"
down_revision: str | Sequence[str] | None = "c5cd363a27c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolio_holdings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("asset_class", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("avg_cost", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_portfolio_holdings_symbol"), "portfolio_holdings", ["symbol"], unique=True)
    op.create_table(
        "price_alerts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("condition", sa.String(length=10), nullable=False),
        sa.Column("target_price", sa.Float(), nullable=False),
        sa.Column("triggered", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("triggered_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_price_alerts_symbol"), "price_alerts", ["symbol"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_price_alerts_symbol"), table_name="price_alerts")
    op.drop_table("price_alerts")
    op.drop_index(op.f("ix_portfolio_holdings_symbol"), table_name="portfolio_holdings")
    op.drop_table("portfolio_holdings")
    # ### end Alembic commands ###
